### ISSUE TITLE
Use Cloudflare's scoped API tokens instead?

### ISSUE THREAD

**Issue by xxdesmus** [simonpainter/pyflare#11]
https://blog.cloudflare.com/api-tokens-general-availability/

Much safer to user an API token scoped for the exact permissions and the specific domain you want to update.

I have not been able to figure out the right combination of permissions this app needs -- so I figured I'd drop you a message assuming you'd quickly be able to figure out what your app is doing and translate that into the minimum amount of access you need to do it.

p.s. I work at Cloudflare -- thanks for creating this, very handy app.

**Comment by simonpainter** [comment]
Thanks for the input, I have pushed a change to accommodate api tokens and updated the readme accordingly.

**Comment by xxdesmus** [comment]
Hi there, thanks for the very quick fix!

I might be doing something wrong, but this doesn't seem to be working for me.

When I use the following config.json I encounter the error below:

```
{
        "items": [{
                "token": "XXXXXXX",
                "zone": "DOMAIN",
                "record": "SUB.DOMAIN",
                "ttl": "1",
                "proxied": 0
        }]
}
```


```
Traceback (most recent call last):
  File "./pyflare.py", line 52, in <module>
    email = item['email']
KeyError: 'email'
```

Is it required to provide an email and API key even when just using a scoped API token?

**Comment by simonpainter** [comment]
You are absolutely correct - give me about 5 mins because that's a very quick fix. In the meantime please can you pull from Refried-Bean/pyflare instead as I have moved all development to that fork.

**Comment by xxdesmus** [comment]
Yep — will do that now. Thanks!

**Comment by simonpainter** [comment]
Just pushed fix there.

**Comment by xxdesmus** [comment]
Just to reuse the same issue — I'm getting a different error now (same config file) →

Traceback (most recent call last):

  File "./ pyflare.py ( http://pyflare.py/ ) ", line 65, in <module>

    print(cf(zone,record,ttl, proxied))

  File "./ pyflare.py ( http://pyflare.py/ ) ", line 37, in __call__

    zone_id = cf.zones(zone)['result'][0]['id']

TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by simonpainter** [comment]
Are you sure you have given the necessary permissions to your token? I
found I needed the following:
"All zones - Zone:Read, DNS:Edit"

**Comment by xxdesmus** [comment]
I was limiting it to 1 zone — all zones works. Sorry about that.

**Comment by simonpainter** [comment]
No worries - glad you got sorted. In order to list the zone to get the zone
id it needs to have read permissions to all of the zones and then it only
needs the DNS edit for the specific zones. Will get round to updating the
docs with the tightest permissions I can get.
