### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by ghost** [simonpainter/pyflare#5]
I created a config.json and then run the script.

Error:
```
Traceback (most recent call last):

  File "pyflare.py", line 53, in <module>

    print(cf(zone,record))

  File "pyflare.py", line 35, in __call__

    zone_id = cf.zones(zone)['result'][0]['id']

TypeError: 'NoneType' object is not subscriptable

```

**Comment by simonpainter** [comment]
So the zone specified in your config file does not appear to match what is in your Cloudflare account. I'll drop in some more error handling but in the meantime could you send me the config file (minus the key). I am specifically interested in the zone and record fields. You can email me using my GitHub name at gmail.com

**Comment by mroettgen** [comment]
Did you manage to fix this? If yes, how? I seem to be stuck with the same issue

**Comment by simonpainter** [comment]
I am guessing that original poster resolved the issue by correcting the config file. Note that there is detail on the format of the config file now included in the README.md file.
